-- LEFT JOIN
SELECT * FROM PETS
LEFT JOIN OWNERS
ON OWNERS.OWNERID = PETS.OWNERID;

SELECT PETS.NAME, OWNERS.NAME FROM PETS
LEFT JOIN OWNERS
ON OWNERS.OWNERID = PETS.OWNERID;

-- TIPS AND TRICKS
-- ALIASES FOR TABLE. Select pets and owners whose first letter in names are equal
SELECT P.NAME, O.NAME
FROM PETS AS P
LEFT JOIN OWNERS AS O
ON O.OWNERID = P.OWNERID
WHERE LEFT(P.NAME, 1) = LEFT(O.NAME, 1);

SELECT P.NAME, O.NAME
FROM PETS P
LEFT JOIN OWNERS O
ON O.OWNERID = P.OWNERID
WHERE LEFT(P.NAME, 1) = LEFT(O.NAME, 1);

-- ALIASES FOR TABLES. 
SELECT P.NAME AS PETNAME, O.NAME AS OWNERNAME
FROM PETS AS P
LEFT JOIN OWNERS AS O
ON O.OWNERID = P.OWNERID
WHERE LEFT(P.NAME, 1) = LEFT(O.NAME, 1);

SELECT P.NAME PETNAME, O.NAME OWNERNAME
FROM PETS P
LEFT JOIN OWNERS O
ON O.OWNERID = P.OWNERID
WHERE LEFT(P.NAME, 1) = LEFT(O.NAME, 1);

-- RIGHT JOIN
SELECT P.NAME, O.NAME
FROM OWNERS AS O
RIGHT JOIN PETS P
ON P.OWNERID = O.OWNERID;

-- INNER TABLE
SELECT *
FROM PETS AS P
INNER JOIN PROCEDUREHISTORY AS H
ON P.PETID = H.PETID;

-- FULL OUTER JOIN
SELECT *
FROM PETS AS P
FULL OUTER JOIN PROCEDUREHISTORY AS H
ON P.PETID = H.PETID;

-- JOINING ON MULTIPLE FIELDS
SELECT H.PETID, H.PROCEDUREDATE, D.PROCEDURETYPE, D.DESCRIPTION, D.PRICE
FROM PROCEDUREHISTORY AS H
LEFT JOIN PROCEDUREDETAILS AS D
ON H.PROCEDURETYPE = D.PROCEDURETYPE
AND H.PROCEDURESUBCODE = D.PROCEDURESUBCODE;

-- COMPLEX JOINS
SELECT 
	P.PETID,
	P.NAME,
	O.NAME AS OWNERNAME,
	H.PROCEDUREDATE,
	D.PROCEDURETYPE,
	D.DESCRIPTION,
	D.PRICE
FROM PETS AS P
LEFT JOIN OWNERS AS O
ON P.OWNERID = O.OWNERID
LEFT JOIN PROCEDUREHISTORY AS H
ON P.PETID = H.PETID
LEFT JOIN PROCEDUREDETAILS AS D
ON H.PROCEDURETYPE = D.PROCEDURETYPE
AND H.PROCEDURESUBCODE = D.PROCEDURESUBCODE
ORDER BY H.PROCEDUREDATE;

-- CROSS JOIN (WILL SHOW ALL POSSIBLE COMBINATIONS OF TWO(OR MORE) TABLES)
SELECT
	P.PETID,
	P.NAME AS PETNAME,
	O.NAME AS OWNERNAME
FROM PETS AS P
CROSS JOIN OWNERS AS O
ORDER BY PETNAME;